// Generated by gencpp from file point_navigation/goToPoint.msg
// DO NOT EDIT!


#ifndef POINT_NAVIGATION_MESSAGE_GOTOPOINT_H
#define POINT_NAVIGATION_MESSAGE_GOTOPOINT_H

#include <ros/service_traits.h>


#include <point_navigation/goToPointRequest.h>
#include <point_navigation/goToPointResponse.h>


namespace point_navigation
{

struct goToPoint
{

typedef goToPointRequest Request;
typedef goToPointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct goToPoint
} // namespace point_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::point_navigation::goToPoint > {
  static const char* value()
  {
    return "600260651fd011534c1d100c4ede3201";
  }

  static const char* value(const ::point_navigation::goToPoint&) { return value(); }
};

template<>
struct DataType< ::point_navigation::goToPoint > {
  static const char* value()
  {
    return "point_navigation/goToPoint";
  }

  static const char* value(const ::point_navigation::goToPoint&) { return value(); }
};


// service_traits::MD5Sum< ::point_navigation::goToPointRequest> should match 
// service_traits::MD5Sum< ::point_navigation::goToPoint > 
template<>
struct MD5Sum< ::point_navigation::goToPointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::point_navigation::goToPoint >::value();
  }
  static const char* value(const ::point_navigation::goToPointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::point_navigation::goToPointRequest> should match 
// service_traits::DataType< ::point_navigation::goToPoint > 
template<>
struct DataType< ::point_navigation::goToPointRequest>
{
  static const char* value()
  {
    return DataType< ::point_navigation::goToPoint >::value();
  }
  static const char* value(const ::point_navigation::goToPointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::point_navigation::goToPointResponse> should match 
// service_traits::MD5Sum< ::point_navigation::goToPoint > 
template<>
struct MD5Sum< ::point_navigation::goToPointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::point_navigation::goToPoint >::value();
  }
  static const char* value(const ::point_navigation::goToPointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::point_navigation::goToPointResponse> should match 
// service_traits::DataType< ::point_navigation::goToPoint > 
template<>
struct DataType< ::point_navigation::goToPointResponse>
{
  static const char* value()
  {
    return DataType< ::point_navigation::goToPoint >::value();
  }
  static const char* value(const ::point_navigation::goToPointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POINT_NAVIGATION_MESSAGE_GOTOPOINT_H
