// Generated by gencpp from file point_navigation/goToPointRequest.msg
// DO NOT EDIT!


#ifndef POINT_NAVIGATION_MESSAGE_GOTOPOINTREQUEST_H
#define POINT_NAVIGATION_MESSAGE_GOTOPOINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace point_navigation
{
template <class ContainerAllocator>
struct goToPointRequest_
{
  typedef goToPointRequest_<ContainerAllocator> Type;

  goToPointRequest_()
    : tf_prefix()
    , pose()  {
    }
  goToPointRequest_(const ContainerAllocator& _alloc)
    : tf_prefix(_alloc)
    , pose(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _tf_prefix_type;
  _tf_prefix_type tf_prefix;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::point_navigation::goToPointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::point_navigation::goToPointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct goToPointRequest_

typedef ::point_navigation::goToPointRequest_<std::allocator<void> > goToPointRequest;

typedef boost::shared_ptr< ::point_navigation::goToPointRequest > goToPointRequestPtr;
typedef boost::shared_ptr< ::point_navigation::goToPointRequest const> goToPointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::point_navigation::goToPointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::point_navigation::goToPointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace point_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::point_navigation::goToPointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::point_navigation::goToPointRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::point_navigation::goToPointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::point_navigation::goToPointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::point_navigation::goToPointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::point_navigation::goToPointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::point_navigation::goToPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "724e2bc4e27a5035d8f96bd8c884c897";
  }

  static const char* value(const ::point_navigation::goToPointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x724e2bc4e27a5035ULL;
  static const uint64_t static_value2 = 0xd8f96bd8c884c897ULL;
};

template<class ContainerAllocator>
struct DataType< ::point_navigation::goToPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "point_navigation/goToPointRequest";
  }

  static const char* value(const ::point_navigation::goToPointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::point_navigation::goToPointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string tf_prefix\n\
geometry_msgs/Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::point_navigation::goToPointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::point_navigation::goToPointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tf_prefix);
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct goToPointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::point_navigation::goToPointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::point_navigation::goToPointRequest_<ContainerAllocator>& v)
  {
    s << indent << "tf_prefix: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.tf_prefix);
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
  }
};

} // namespace message_operations
} // namespace ros

#endif // POINT_NAVIGATION_MESSAGE_GOTOPOINTREQUEST_H
